abstract class Rune
{   
  //Rune Variables 
  String type; //Keeps track of the type of rune
  float x; //Keeps track of the rune's x position 
  float y; //Keeps track of the rune's y position 
  float size; //Keeps track of the rune's radius - depends on the grid size
  float speedX; 
  float speedY; 
  
  Rune(String type, float x, float y, float size)
  {
     this.type = type; 
     this.x = x; 
     this.y = y; 
     this.size = size; 
  }
  
  //This method will define how to draw the rune to the screen
  abstract void drawRune(); 
  
  //This method will define how to draw the attack generated by the rune, as well as it's effects
  abstract void attack(); 
  
  
  
  
  
  
}
